"use client";

import { useQuery } from "@tanstack/react-query";
import { getEmergencyCard } from "@/lib/api";
import { AlertTriangle, Phone, Droplets, Pill, ShieldAlert } from "lucide-react";

export default function EmergencyCardPage() {
  const { data: card, isLoading } = useQuery({
    queryKey: ["emergency-card"],
    queryFn: () => getEmergencyCard().then((r) => r.data),
  });

  if (isLoading) {
    return (
      <div className="flex items-center justify-center h-96">
        <div className="animate-spin rounded-full h-10 w-10 border-4 border-red-500 border-t-transparent" />
      </div>
    );
  }

  return (
    <div className="p-8 max-w-2xl mx-auto">
      <div className="flex items-center gap-3 mb-6">
        <ShieldAlert className="w-7 h-7 text-red-500" />
        <div>
          <h1 className="text-2xl font-bold text-red-600">Emergency Card</h1>
          <p className="text-sm text-gray-500">Show this to emergency responders</p>
        </div>
      </div>

      <div className="bg-red-50 border-2 border-red-200 rounded-2xl p-6 space-y-5">
        {/* Patient */}
        <div className="border-b border-red-200 pb-4">
          <div className="text-red-500 text-xs font-semibold uppercase tracking-wide mb-1">Patient</div>
          <div className="text-2xl font-bold text-red-800">{card?.full_name}</div>
        </div>

        {/* Blood Group */}
        <div className="flex items-center gap-3">
          <Droplets className="w-5 h-5 text-red-500" />
          <div>
            <div className="text-xs text-gray-500">Blood Group</div>
            <div className="font-bold text-lg text-red-700">{card?.blood_group || "Unknown"}</div>
          </div>
        </div>

        {/* Allergies */}
        <div>
          <div className="flex items-center gap-2 text-xs text-gray-500 uppercase font-semibold mb-2">
            <AlertTriangle className="w-4 h-4 text-orange-500" /> Allergies
          </div>
          {card?.allergies?.length > 0 ? (
            <div className="flex flex-wrap gap-2">
              {card.allergies.map((a: string) => (
                <span key={a} className="bg-red-100 text-red-700 px-3 py-1 rounded-full text-sm font-medium">
                  {a}
                </span>
              ))}
            </div>
          ) : (
            <p className="text-gray-400 text-sm">No known allergies</p>
          )}
        </div>

        {/* Active Medications */}
        <div>
          <div className="flex items-center gap-2 text-xs text-gray-500 uppercase font-semibold mb-2">
            <Pill className="w-4 h-4 text-blue-500" /> Current Medications
          </div>
          {card?.active_medications?.length > 0 ? (
            <ul className="space-y-1">
              {card.active_medications.map((m: any, i: number) => (
                <li key={i} className="text-sm text-gray-700">
                  <span className="font-semibold">{m.name}</span> — {m.dosage} {m.frequency}
                </li>
              ))}
            </ul>
          ) : (
            <p className="text-gray-400 text-sm">No active medications</p>
          )}
        </div>

        {/* Emergency Contact */}
        {card?.emergency_contact_name && (
          <div className="border-t border-red-200 pt-4">
            <div className="flex items-center gap-2 text-xs text-gray-500 uppercase font-semibold mb-2">
              <Phone className="w-4 h-4 text-green-500" /> Emergency Contact
            </div>
            <div className="font-semibold">{card.emergency_contact_name}</div>
            <div className="text-sm text-gray-600">{card.emergency_contact_phone}</div>
          </div>
        )}

        {/* Medical Conditions */}
        {card?.medical_conditions?.length > 0 && (
          <div className="border-t border-red-200 pt-4">
            <div className="text-xs text-gray-500 uppercase font-semibold mb-2">Medical Conditions</div>
            <div className="text-sm text-gray-700">{card.medical_conditions.join(", ")}</div>
          </div>
        )}
      </div>

      <p className="text-xs text-gray-400 mt-4 text-center">
        Generated by MediGuard · Not a substitute for professional medical advice
      </p>
    </div>
  );
}
